export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILURE = 'GET_CONTACTS_FAILURE';
export const GET_CONTACTDETAIL = 'GET_CONTACTDETAIL';
export const GET_CONTACTDETAIL_SUCCESS = 'GET_CONTACTDETAIL_SUCCESS';
export const GET_CONTACTDETAIL_FAILURE = 'GET_CONTACTDETAIL_FAILURE';

export const GET_UNREGISTERED_CONTACTS = 'GET_UNREGISTERED_CONTACTS';

export const GET_UNSUBSCRIBED_CONTACTS = 'GET_UNSUBSCRIBED_CONTACTS';
export const GET_UNSUBSCRIBED_CONTACTS_SUCCESS =
  'GET_UNSUBSCRIBED_CONTACTS_SUCCESS';
export const GET_UNSUBSCRIBED_CONTACTS_FAILURE =
  'GET_UNSUBSCRIBED_CONTACTS_FAILURE';
