export const ADD_TIMESLOT = 'ADD_TIMESLOT';
export const ADD_TIMESLOT_SUCCESS = 'ADD_TIMESLOT_SUCCESS';
export const ADD_TIMESLOT_FAILURE = 'ADD_TIMESLOT_FAILURE';

export const REMOVE_TIMESLOT = 'REMOVE_TIMESLOT';
export const REMOVE_TIMESLOT_SUCCESS = 'REMOVE_TIMESLOT_SUCCESS';
export const REMOVE_TIMESLOT_FAILURE = 'REMOVE_TIMESLOT_FAILURE';

export const GET_TIMESLOTS = 'GET_TIMESLOTS';
export const GET_TIMESLOTS_SUCCESS = 'GET_TIMESLOTS_SUCCESS';
export const GET_TIMESLOTS_FAILURE = 'GET_TIMESLOTS_FAILURE';

export const GET_APPOINTMENTS = 'GET_APPOINTMENTS'
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAILURE = 'GET_APPOINTMENTS_FAILURE';

export const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT';
export const REMOVE_APPOINTMENT_SUCCESS = 'REMOVE_APPOINTMENT_SUCCESS';
export const REMOVE_APPOINTMENT_FAILURE = 'REMOVE_APPOINTMENT_FAILURE';
