require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'


platform :ios, '11.0'

pod 'Firebase/Crashlytics'

# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

target 'TikText' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  
  pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

  target 'TikTextTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper' => '0.74.0' })
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'TikText-tvOS' do
  # Pods for TikText-tvOS

  target 'TikText-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
