export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const INITIALIZE_AUTH_START = 'INITIALIZE_AUTH_START';
export const INITIALIZE_AUTH_FINISH = 'INITIALIZE_AUTH_FINISH';

export const PUSH_TOKEN = 'PUSH_TOKEN'