export const ADD_SOCIAL_MEDIA = 'ADD_SOCIAL_MEDIA';
export const ADD_SOCIAL_MEDIA_SUCCESS = 'ADD_SOCIAL_MEDIA_SUCCESS';
export const ADD_SOCIAL_MEDIA_FAILURE = 'ADD_SOCIAL_MEDIA_FAILURE';

export const REMOVE_SOCIAL_MEDIA = 'REMOVE_SOCIAL_MEDIA';
export const REMOVE_SOCIAL_MEDIA_SUCCESS = 'REMOVE_SOCIAL_MEDIA_SUCCESS';
export const REMOVE_SOCIAL_MEDIA_FAILURE = 'REMOVE_SOCIAL_MEDIA_FAILURE';

export const GET_SOCIAL_MEDIA = 'GET_SOCIAL_MEDIA';
export const GET_SOCIAL_MEDIA_SUCCESS = 'GET_SOCIAL_MEDIA_SUCCESS';
export const GET_SOCIAL_MEDIA_FAILURE = 'GET_SOCIAL_MEDIA_FAILURE';
